### ISSUE TITLE
Internal Library Error while trying to upload a new file

### ISSUE THREAD

**Issue by ghost** [FleekHQ/fleek-storage-js#38]
I was trying to upload many "objects" to fleek and sometimes I receive this be cause may be request fail.

```bash
/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: Cannot read properties of null (reading 'ETag')
    at Request.<anonymous> (/Users/ww/git/project-fleek/node_modules/@fleekhq/fleek-storage-js/utils/upload-file.js:8:21)
    at Request.callListeners (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/ww/git/project-fleek/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/ww/git/project-fleek/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'TypeError',
  time: 2022-01-12T22:45:58.056Z
}
```

I don't know really to say. just reporting unexpected error may be

**Comment by lubert** [comment]
Should be fixed by https://github.com/FleekHQ/fleek-storage-js/pull/37 if it gets merged in
